# filename: app.py
# Code Generated by Sidekick is for learning and experimentation purposes only.

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components
import itertools
from pathlib import Path
from typing import List, Dict, Any
import numpy as np
import re
import plotly.express as px


# We only import Bronze since that is working fine.
from src.bronze_processing import collect_bronze_profiles


# ==========================================
# --- EMBEDDED SILVER PROCESSING LOGIC ---
# ==========================================


def detect_anomalies(
    file_name: str,
    bronze_dir: str = "data/1_bronze"
) -> Dict[str, Any]:
    """Scans for negatives and ALL date columns."""
    bronze_path = Path(bronze_dir) / file_name

    if not bronze_path.exists():
        return {"negatives": {}, "date_columns": {}}

    df = (
        pd.read_csv(bronze_path, keep_default_na=False, dtype=str)
        .replace("", np.nan)
    )

    anomalies = {"negatives": {}, "date_columns": {}}

    # 1. Detect negative values
    for col in df.columns:
        numeric_col = pd.to_numeric(df[col], errors="coerce")

        if not numeric_col.isnull().all():
            neg_count = (numeric_col < 0).sum()

            if neg_count > 0:
                anomalies["negatives"][col] = int(neg_count)

    # 2. Detect ALL Date Columns
    def get_date_format(date_str):
        if pd.isna(date_str):
            return None

        date_str = str(date_str).strip()

        if re.match(r"^\d{4}-\d{1,2}-\d{1,2}", date_str):
            return "YYYY-MM-DD"

        if re.match(r"^\d{1,2}[/-]\d{1,2}[/-]\d{4}", date_str):
            return "MM/DD/YYYY"

        if re.match(r"^\d{1,2}-[A-Za-z]{3}-\d{4}", date_str):
            return "DD-Mon-YYYY"

        if pd.to_datetime(date_str, errors="coerce") is not pd.NaT:
            return "Other/Mixed"

        return None

    for col in df.columns:
        series = df[col].dropna()

        if series.empty:
            continue

        is_date_col = "date" in col.lower()

        if not is_date_col and series.dtype == "object":
            sample = series.head(50)
            parsed = pd.to_datetime(sample, errors="coerce")

            if parsed.notna().sum() > (len(sample) * 0.5):
                if not pd.to_numeric(sample, errors="coerce").notna().all():
                    is_date_col = True

        if is_date_col:
            sample_for_formats = series.sample(
                n=min(100, len(series)),
                random_state=1
            )

            detected = {
                fmt
                for fmt in sample_for_formats.apply(get_date_format)
                if fmt is not None
            }

            if not detected:
                detected = {"Unknown/Mixed"}

            anomalies["date_columns"][col] = sorted(list(detected))

    return anomalies


def clean_bronze_csv(
    file_name: str,
    cols_to_fix_negatives: List[str] = None,
    target_date_formats: Dict[str, str] = None,
    bronze_dir: str = "data/1_bronze",
    silver_dir: str = "data/2_silver"
) -> Dict[str, Any]:
    if cols_to_fix_negatives is None:
        cols_to_fix_negatives = []

    if target_date_formats is None:
        target_date_formats = {}

    df = pd.read_csv(Path(bronze_dir) / file_name, keep_default_na=True)

    before_df = df.copy(deep=True)
    after_df = df.copy()
    audit_log = []

    original_columns = list(after_df.columns)

    cleaned_columns = [
        str(col).strip().lower().replace(" ", "_")
        for col in original_columns
    ]

    after_df.columns = cleaned_columns
    col_map = dict(zip(original_columns, cleaned_columns))

    if original_columns != cleaned_columns:
        audit_log.append(
            f"Standardized {len(cleaned_columns)} column name(s)."
        )

    date_code_map = {
        "YYYY-MM-DD": "%Y-%m-%d",
        "MM/DD/YYYY": "%m/%d/%Y",
        "DD-MM-YYYY": "%d-%m-%Y",
        "DD-Mon-YYYY": "%d-%b-%Y",
    }

    for orig_col, target_format in target_date_formats.items():
        clean_col = col_map.get(orig_col, orig_col)

        if clean_col in after_df.columns:

            def safe_parse(value):
                if pd.isna(value) or str(value).strip() == "":
                    return pd.NaT

                return pd.to_datetime(str(value).strip(), errors="coerce")

            parsed_series = pd.to_datetime(
                after_df[clean_col].apply(safe_parse)
            )

            format_code = date_code_map.get(
                target_format,
                "%Y-%m-%d"
            )

            after_df[clean_col] = parsed_series.dt.strftime(format_code)

            audit_log.append(
                f"Standardized dates in '{clean_col}' "
                f"to format: {target_format}."
            )

    if cols_to_fix_negatives:
        mapped_fix_negatives = [
            col_map.get(col, col)
            for col in cols_to_fix_negatives
        ]

        for col in mapped_fix_negatives:
            if (
                col in after_df.columns
                and pd.api.types.is_numeric_dtype(after_df[col])
            ):
                neg_mask = after_df[col] < 0

                if neg_mask.any():
                    after_df[col] = after_df[col].abs()

                    audit_log.append(
                        f"Converted {neg_mask.sum()} negative value(s) "
                        f"to positive in '{col}'."
                    )

    for col in after_df.columns:
        if after_df[col].dtype == "object":
            after_df[col] = after_df[col].apply(
                lambda value: value.strip()
                if isinstance(value, str)
                else value
            )

        if after_df[col].isnull().any():
            null_count = after_df[col].isnull().sum()

            fill_val = (
                0
                if pd.api.types.is_numeric_dtype(after_df[col])
                else "Unknown"
            )

            after_df[col] = after_df[col].fillna(fill_val)

            audit_log.append(
                f"Filled {null_count} missing value(s) in '{col}' "
                f"with '{fill_val}'."
            )

    if not audit_log:
        audit_log.append(
            "Data was already clean; no modifications were necessary."
        )

    silver_path = Path(silver_dir)
    silver_path.mkdir(parents=True, exist_ok=True)

    after_df.to_csv(silver_path / file_name, index=False)

    comparison_rows = []

    for i in range(len(before_df)):
        b_row = before_df.iloc[i]
        a_row = after_df.iloc[i]

        for orig_col, clean_col in col_map.items():
            b_val = b_row.get(orig_col)
            a_val = a_row.get(clean_col)

            b_str = str(b_val)
            a_str = str(a_val)

            if pd.isna(b_val):
                b_str = "Null"

            if pd.isna(a_val):
                a_str = "Null"

            if b_str != a_str:
                comparison_rows.append(
                    {
                        "Row #": i + 1,
                        "Column": orig_col,
                        "Before": b_str,
                        "After": a_str,
                    }
                )

        if len(comparison_rows) >= 15:
            break

    return {
        "audit_log": audit_log,
        "comparison_dataframe": pd.DataFrame(comparison_rows),
    }


def evaluate_silver_join_keys(
    file_names: List[str],
    silver_dir: str = "data/2_silver"
):
    profiles = []
    potential_keys = []

    for file_name in file_names:
        path = Path(silver_dir) / file_name

        if path.exists():
            profiles.append(
                {
                    "file": file_name,
                    "columns": set(
                        pd.read_csv(path, nrows=0).columns
                    ),
                }
            )

    if len(profiles) > 1:
        for profile_1, profile_2 in itertools.combinations(
            profiles,
            2
        ):
            common = sorted(
                list(
                    profile_1["columns"].intersection(
                        profile_2["columns"]
                    )
                )
            )

            if common:
                potential_keys.append(
                    {
                        "file_1": profile_1["file"],
                        "file_2": profile_2["file"],
                        "common_columns": common,
                    }
                )

    return potential_keys


# ==========================================
# --- EMBEDDED GOLD PROCESSING LOGIC ---
# ==========================================


def create_gold_join(
    file_1: str,
    file_2: str,
    join_keys: List[str],
    silver_dir: str = "data/2_silver",
    gold_dir: str = "data/3_gold"
) -> str:
    """Merges two cleaned Silver tables and saves the enriched dataset to Gold."""
    df1 = pd.read_csv(Path(silver_dir) / file_1)
    df2 = pd.read_csv(Path(silver_dir) / file_2)

    joined_df = pd.merge(
        df1,
        df2,
        on=join_keys,
        how="left",
        suffixes=("_base", "_enriched"),
    )

    joined_name = (
        f"joined_{Path(file_1).stem}_{Path(file_2).stem}.csv"
    )

    gold_path = Path(gold_dir)
    gold_path.mkdir(parents=True, exist_ok=True)

    joined_df.to_csv(gold_path / joined_name, index=False)

    return joined_name


def generate_gold_insights(
    file_name: str,
    is_joined: bool = False,
    silver_dir: str = "data/2_silver",
    gold_dir: str = "data/3_gold"
) -> Dict[str, Any]:
    """Generates business summaries, takeaways, and Plotly charts."""
    read_path = (
        Path(gold_dir) / file_name
        if is_joined
        else Path(silver_dir) / file_name
    )

    if not read_path.exists():
        raise FileNotFoundError(f"Source file not found: {read_path}")

    df = pd.read_csv(read_path)

    numeric_cols = list(
        df.select_dtypes(include=[np.number]).columns
    )

    object_cols = list(
        df.select_dtypes(include=["object"]).columns
    )

    date_cols = [
        col
        for col in df.columns
        if "date" in col.lower() or "time" in col.lower()
    ]

    for date_col in date_cols:
        if date_col in object_cols:
            object_cols.remove(date_col)

    measurable_numerics = [
        col
        for col in numeric_cols
        if not any(
            word in col.lower()
            for word in ["id", "zip", "code"]
        )
    ]

    primary_numeric = (
        measurable_numerics[0]
        if measurable_numerics
        else numeric_cols[0]
        if numeric_cols
        else None
    )

    grouping_col = None

    if object_cols:
        priority_cats = [
            col
            for col in object_cols
            if any(
                word in col.lower()
                for word in [
                    "region",
                    "city",
                    "state",
                    "category",
                    "segment",
                    "store_name",
                ]
            )
        ]

        valid_cats = [
            col
            for col in object_cols
            if 1 < df[col].nunique() < 100
        ]

        if priority_cats:
            grouping_col = priority_cats[0]
        elif valid_cats:
            grouping_col = valid_cats[0]
        else:
            grouping_col = object_cols[0]

    summary_df = pd.DataFrame()
    insights = []

    bar_chart = None
    line_chart = None
    treemap_chart = None

    # Aggregations and Bar Chart
    if primary_numeric and grouping_col:
        summary_df = (
            df.groupby(grouping_col)[primary_numeric]
            .agg(
                sum="sum",
                average="mean",
                count="count",
            )
            .reset_index()
        )

        summary_df = (
            summary_df
            .sort_values("sum", ascending=False)
            .reset_index(drop=True)
        )

        top_cat = summary_df.iloc[0]

        insights.append(
            f"🏆 **Top Performer:** `{top_cat[grouping_col]}` "
            f"leads with a total "
            f"{primary_numeric.replace('_', ' ')} of "
            f"**{top_cat['sum']:,.2f}**."
        )

        insights.append(
            f"📊 **Averages:** The overall average "
            f"{primary_numeric.replace('_', ' ')} per record is "
            f"**{df[primary_numeric].mean():,.2f}**."
        )

        bar_chart = px.bar(
            summary_df.head(10),
            x=grouping_col,
            y="sum",
            title=(
                f"Top 10 "
                f"{grouping_col.replace('_', ' ').title()} by Total "
                f"{primary_numeric.replace('_', ' ').title()}"
            ),
            template="plotly_white",
        )

    elif grouping_col:
        summary_df = (
            df[grouping_col]
            .value_counts()
            .reset_index(name="row_count")
        )

        summary_df.columns = [grouping_col, "row_count"]

        top_cat = summary_df.iloc[0]

        insights.append(
            f"🏆 **Highest Frequency:** `{top_cat[grouping_col]}` "
            f"is the most common, appearing "
            f"**{top_cat['row_count']:,}** times."
        )

        insights.append(
            f"📊 **Distribution:** The dataset contains "
            f"{df[grouping_col].nunique()} unique categories in "
            f"`{grouping_col}`."
        )

        bar_chart = px.bar(
            summary_df.head(10),
            x=grouping_col,
            y="row_count",
            title=(
                f"Top 10 "
                f"{grouping_col.replace('_', ' ').title()} by Volume"
            ),
            template="plotly_white",
        )

    # Line Chart: Trend over time
    if date_cols and primary_numeric:
        date_col = date_cols[0]

        trend_df = (
            df.groupby(date_col)[primary_numeric]
            .sum()
            .reset_index()
            .sort_values(date_col)
        )

        line_chart = px.line(
            trend_df,
            x=date_col,
            y=primary_numeric,
            markers=True,
            title=(
                f"Trend of "
                f"{primary_numeric.replace('_', ' ').title()} over Time"
            ),
            template="plotly_white",
        )

    elif date_cols:
        date_col = date_cols[0]

        trend_df = (
            df[date_col]
            .value_counts()
            .reset_index(name="row_count")
            .sort_values(date_col)
        )

        line_chart = px.line(
            trend_df,
            x=date_col,
            y="row_count",
            markers=True,
            title="Data Volume over Time",
            template="plotly_white",
        )

    # Treemap: Geographic or Hierarchical
    location_columns = [
        col
        for col in [
            "region",
            "state",
            "city",
            "category",
            "subcategory",
        ]
        if col in df.columns
    ]

    if len(location_columns) >= 2:
        loc_df = (
            df.groupby(location_columns)
            .size()
            .reset_index(name="count")
        )

        treemap_chart = px.treemap(
            loc_df,
            path=[px.Constant("All")] + location_columns,
            values="count",
            title=(
                "Hierarchical Distribution "
                "(e.g. Region -> State -> City)"
            ),
        )

    # Save summary to Gold layer
    gold_path = Path(gold_dir)
    gold_path.mkdir(parents=True, exist_ok=True)

    if not summary_df.empty:
        summary_df.to_csv(
            gold_path / f"gold_summary_{file_name}",
            index=False,
        )

    return {
        "summary_df": summary_df,
        "insights": insights,
        "bar_chart": bar_chart,
        "line_chart": line_chart,
        "treemap_chart": treemap_chart,
    }


# ==========================================
# --- MAIN APP ROUTING & REAL-TIME STATE ---
# ==========================================


st.set_page_config(
    page_title="Medallion Data Pipeline",
    page_icon="🧭",
    layout="wide",
)


for key in [
    "step",
    "uploaded_file_names",
    "bronze_profiles",
    "silver_results",
    "gold_results",
    "joined_files",
    "last_step",
]:
    if key not in st.session_state:
        st.session_state[key] = (
            []
            if key in [
                "uploaded_file_names",
                "bronze_profiles",
                "joined_files",
            ]
            else {}
            if "results" in key
            else "landing"
            if key in ["step", "last_step"]
            else None
        )


# Track the navigation state before rendering the current page.
# The scroll script is executed after the page has rendered.
step_changed = (
    st.session_state.step != st.session_state.last_step
)


def scroll_to_top() -> None:
    """
    Scroll all likely Streamlit scroll containers to the top.

    The delayed retries handle Streamlit's asynchronous page rendering.
    """
    components.html(
        """
        <script>
            (() => {
                const scrollToTop = () => {
                    const doc = window.parent.document;

                    const containers = [
                        doc.querySelector(
                            '[data-testid="stAppViewContainer"]'
                        ),
                        doc.querySelector('[data-testid="stMain"]'),
                        doc.querySelector('section.main'),
                        doc.querySelector('.main')
                    ].filter(Boolean);

                    containers.forEach((container) => {
                        container.scrollTop = 0;
                        container.scrollLeft = 0;
                    });

                    window.parent.scrollTo(0, 0);
                    doc.documentElement.scrollTop = 0;
                    doc.body.scrollTop = 0;
                };

                requestAnimationFrame(scrollToTop);
                setTimeout(scrollToTop, 100);
                setTimeout(scrollToTop, 300);
            })();
        </script>
        """,
        height=0,
    )


# Create a placeholder for the tracker.
# The tracker content is injected after the main page content.
tracker_placeholder = st.empty()


# --- Main App Body ---

if st.session_state.step == "landing":
    st.markdown(
        "<h1 style='text-align: center;'>"
        "🏗️ AI-Powered Medallion Pipeline"
        "</h1>",
        unsafe_allow_html=True,
    )

    st.markdown(
        "<p style='text-align: center; font-size: 1.2rem; color: gray;'>"
        "Your intelligent, end-to-end data engineering agent. "
        "Go from raw CSVs to business-ready insights in seconds."
        "</p>",
        unsafe_allow_html=True,
    )

    st.write("")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.info(
            "### 🥉 Bronze\n"
            "**Ingestion & Profiling**\n\n"
            "Drop in your raw data. We automatically profile it, "
            "infer data types, and map your metadata. Identify potential "
            "join keys early to prepare for downstream analytics."
        )

    with col2:
        st.warning(
            "### 🥈 Silver\n"
            "**Cleaning & Resolution**\n\n"
            "Detect anomalies, auto-format date fields, strip invisible "
            "text spacing, and resolve missing values with a completely "
            "transparent, live audit trail and analyse potential join "
            "conditions for data."
        )

    with col3:
        st.success(
            "### 🥇 Gold\n"
            "**Enrichment & Insights**\n\n"
            "Merge cleaned datasets dynamically based on inferred "
            "relationships, generate business takeaways, and visualize "
            "your data with interactive charts."
        )

    st.divider()
    st.write("")

    c1, c2, c3 = st.columns([1, 1, 1])

    with c2:
        if st.button(
            "🚀 Start Data Pipeline",
            type="primary",
            use_container_width=True,
        ):
            st.session_state.step = "ingestion"
            st.rerun()


elif st.session_state.step == "ingestion":
    st.title("Bronze Layer: Ingestion & Profiling")

    uploaded_files = st.file_uploader(
        "Upload raw CSV files.",
        type=["csv"],
        accept_multiple_files=True,
    )

    if uploaded_files:
        bundle = collect_bronze_profiles(
            uploaded_files,
            save_dir="data/1_bronze",
        )

        st.session_state.bronze_profiles = bundle.get(
            "profiles",
            [],
        )

        st.session_state.uploaded_file_names = [
            profile["source_file"]
            for profile in st.session_state.bronze_profiles
        ]

        name = st.selectbox(
            "Select a file to view its profile:",
            st.session_state.uploaded_file_names,
            key="selected_file_name",
        )

        profile = next(
            (
                profile
                for profile in st.session_state.bronze_profiles
                if profile["source_file"] == name
            ),
            None,
        )

        if profile:
            st.subheader(f"Profile for: `{name}`")

            rows = profile.get("total_rows", 0)
            columns = profile.get("total_columns", 0)

            c1, c2 = st.columns(2)
            c1.metric("Rows", f"{rows:,}")
            c2.metric("Columns", f"{columns:,}")

            inferred_dtypes = profile.get(
                "columns_with_inferred_dtypes",
                {},
            )

            missing_values = profile.get(
                "missing_values_per_column",
                {},
            )

            st.dataframe(
                pd.DataFrame(
                    {
                        "Column": inferred_dtypes.keys(),
                        "Type": inferred_dtypes.values(),
                        "Missing": [
                            missing_values.get(column, 0)
                            for column in inferred_dtypes.keys()
                        ],
                    }
                )
            )

        st.divider()

        col_nav_1, col_nav_2 = st.columns([1, 6])

        if col_nav_1.button("⬅️ Back to Landing"):
            st.session_state.step = "landing"
            st.rerun()

        if col_nav_2.button(
            "Proceed to Silver Layer ➡️",
            type="primary",
        ):
            st.session_state.step = "silver"
            st.rerun()


elif st.session_state.step == "silver":
    st.title("Silver Layer: Transformations & Anomaly Resolution")

    if not st.session_state.uploaded_file_names:
        st.warning("Please upload files first.")

        if st.button("⬅️ Go Back to Ingestion"):
            st.session_state.step = "ingestion"
            st.rerun()

    else:
        name = st.selectbox(
            "1. Which file to process?",
            st.session_state.uploaded_file_names,
            key="silver_file_selector",
        )

        anomalies = detect_anomalies(name)

        cols_to_fix_negatives = []
        target_date_formats = {}

        if anomalies["negatives"] or anomalies["date_columns"]:
            st.warning("⚠️ **Data Anomalies Detected!**")

            with st.form("anomaly_form"):
                if anomalies["negatives"]:
                    st.write("**Negative Values Detected:**")

                    for col, count in anomalies["negatives"].items():
                        if st.checkbox(
                            f"Fix `{col}` ({count} records)",
                            value=True,
                            key=f"neg_{name}_{col}",
                        ):
                            cols_to_fix_negatives.append(col)

                if anomalies["date_columns"]:
                    st.write("**Date Formatting:**")

                    for col, formats in anomalies[
                        "date_columns"
                    ].items():
                        st.markdown(
                            f"Column: **`{col}`** "
                            f"_(Formats found: {', '.join(formats)})_"
                        )

                        chosen_fmt = st.selectbox(
                            "Select Target Format:",
                            [
                                "YYYY-MM-DD",
                                "MM/DD/YYYY",
                                "DD-MM-YYYY",
                                "DD-Mon-YYYY",
                            ],
                            key=f"date_{name}_{col}",
                        )

                        target_date_formats[col] = chosen_fmt

                submitted = st.form_submit_button(
                    "Run Silver Cleaning with Selections"
                )

            if submitted:
                with st.spinner("Applying transformations..."):
                    st.session_state.silver_results[name] = (
                        clean_bronze_csv(
                            name,
                            cols_to_fix_negatives,
                            target_date_formats,
                        )
                    )

        else:
            if st.button(
                f"Run Standard Cleaning on `{name}`",
                type="primary",
            ):
                with st.spinner("Applying transformations..."):
                    st.session_state.silver_results[name] = (
                        clean_bronze_csv(name, [], {})
                    )

        if name in st.session_state.silver_results:
            st.subheader(f"Results for `{name}`")

            result = st.session_state.silver_results[name]

            st.markdown("**📋 Transformation Audit Log**")

            for log in result.get("audit_log", []):
                st.success(f"✓ {log}")

            comparison_df = result.get("comparison_dataframe")

            if comparison_df is not None and not comparison_df.empty:
                st.markdown(
                    "**🔍 Specific Changed Cells (Sample)**"
                )

                st.dataframe(
                    comparison_df,
                    use_container_width=True,
                )

        st.divider()

        if len(st.session_state.uploaded_file_names) > 1:
            st.subheader("2. Analyze Join Relationships")

            if st.button("Check for Common Columns"):
                with st.spinner("Analyzing..."):
                    files = [
                        file_name
                        for file_name
                        in st.session_state.uploaded_file_names
                        if (
                            Path("data/2_silver") / file_name
                        ).exists()
                    ]

                    if not files:
                        st.warning(
                            "No cleaned files found. Run cleaning first."
                        )

                    else:
                        keys = evaluate_silver_join_keys(files)

                        if keys:
                            st.success(
                                "🔗 **Standardized Join Mappings**"
                            )

                            markdown_table = (
                                "| Source File A | Source File B | "
                                "Join Keys (Standardized Columns) |\n"
                                "| :--- | :--- | :--- |\n"
                            )

                            for mapping in keys:
                                bold_cols = ", ".join(
                                    [
                                        f"`{column}`"
                                        for column
                                        in mapping["common_columns"]
                                    ]
                                )

                                markdown_table += (
                                    f"| 📄 {mapping['file_1']} | "
                                    f"📄 {mapping['file_2']} | "
                                    f"🔑 {bold_cols} |\n"
                                )

                            st.markdown(markdown_table)

                        else:
                            st.warning("No common columns found.")

        st.divider()

        col_nav_1, col_nav_2 = st.columns([1, 6])

        if col_nav_1.button("⬅️ Back to Ingestion"):
            st.session_state.step = "ingestion"
            st.rerun()

        if col_nav_2.button(
            "Proceed to Gold Layer ➡️",
            type="primary",
        ):
            st.session_state.step = "gold"
            st.rerun()


elif st.session_state.step == "gold":
    st.title("Gold Layer: Enrichment & Business Insights")

    cleaned_files = [
        file_name
        for file_name in st.session_state.uploaded_file_names
        if (Path("data/2_silver") / file_name).exists()
    ]

    keys = evaluate_silver_join_keys(cleaned_files)

    if keys:
        st.subheader("1. Create Enriched Datasets (Joins)")

        st.write(
            "Merge your cleaned Silver tables to unlock deeper, "
            "cross-domain insights."
        )

        for mapping in keys:
            col1, col2 = st.columns([3, 1])

            bold_cols = ", ".join(
                [
                    f"`{column}`"
                    for column in mapping["common_columns"]
                ]
            )

            col1.info(
                f"🔗 Join **{mapping['file_1']}** with "
                f"**{mapping['file_2']}** on {bold_cols}"
            )

            if col2.button(
                "Execute Join",
                key=(
                    f"join_{mapping['file_1']}_"
                    f"{mapping['file_2']}"
                ),
            ):
                with st.spinner("Merging datasets..."):
                    joined_name = create_gold_join(
                        mapping["file_1"],
                        mapping["file_2"],
                        mapping["common_columns"],
                    )

                    if joined_name not in st.session_state.joined_files:
                        st.session_state.joined_files.append(
                            joined_name
                        )

                    st.success(
                        f"Successfully created `{joined_name}`!"
                    )

        st.divider()

    st.subheader("2. Generate Business Insights")

    all_analysis_files = (
        cleaned_files + st.session_state.joined_files
    )

    if not all_analysis_files:
        st.warning(
            "No cleaned Silver files available for analysis. "
            "Go back and run the cleaning step."
        )

        if st.button("⬅️ Go Back to Silver"):
            st.session_state.step = "silver"
            st.rerun()

    else:
        target_file = st.selectbox(
            "Select file to analyze (Single or Joined):",
            all_analysis_files,
        )

        is_joined_file = target_file.startswith("joined_")

        if st.button(
            f"Generate Gold Insights for `{target_file}` 🥇",
            type="primary",
        ):
            with st.spinner(
                "Compiling aggregated metrics and trends..."
            ):
                try:
                    st.session_state.gold_results[target_file] = (
                        generate_gold_insights(
                            target_file,
                            is_joined=is_joined_file,
                        )
                    )

                    st.success("Gold processing completed!")

                except Exception as error:
                    st.error(f"Gold Processing Error: {error}")

        if target_file in st.session_state.gold_results:
            result = st.session_state.gold_results[target_file]

            st.subheader("💡 Key Takeaways")

            for insight in result.get("insights", []):
                st.info(insight)

            summary_df = result.get("summary_df")

            if summary_df is not None and not summary_df.empty:
                with st.expander("View Aggregated Summary Data"):
                    st.dataframe(
                        summary_df,
                        use_container_width=True,
                    )

            st.subheader("📈 Visualizations")

            c1, c2 = st.columns(2)

            with c1:
                if result.get("bar_chart"):
                    st.plotly_chart(
                        result["bar_chart"],
                        use_container_width=True,
                    )
                else:
                    st.info(
                        "No categorical distribution chart available."
                    )

            with c2:
                if result.get("line_chart"):
                    st.plotly_chart(
                        result["line_chart"],
                        use_container_width=True,
                    )
                else:
                    st.info(
                        "No time-series trend chart available."
                    )

            if result.get("treemap_chart"):
                st.plotly_chart(
                    result["treemap_chart"],
                    use_container_width=True,
                )

    st.divider()

    col_nav_1, col_nav_2 = st.columns([1, 6])

    if col_nav_1.button("⬅️ Back to Silver"):
        st.session_state.step = "silver"
        st.rerun()

    if col_nav_2.button("🔄 Reset & Start Over"):
        st.session_state.clear()
        st.rerun()


# ==========================================
# --- REAL-TIME GRANULAR PROGRESS RENDER ---
# ==========================================


def calculate_real_time_progress() -> tuple:
    step = st.session_state.step

    if step == "landing":
        return (
            0,
            "Ready to Start",
            "Waiting for pipeline initiation...",
        )

    if step == "ingestion":
        if not st.session_state.uploaded_file_names:
            return (
                10,
                "🥉 Bronze Layer",
                "Waiting for raw CSV uploads...",
            )

        return (
            25,
            "🥉 Bronze Layer",
            "Files Uploaded & Profiled. Ready for Silver.",
        )

    if step == "silver":
        if not st.session_state.silver_results:
            return (
                33,
                "🥈 Silver Layer",
                "Waiting to run transformations...",
            )

        return (
            50,
            "🥈 Silver Layer",
            "Data Cleaned & Anomalies Fixed. Ready for Gold.",
        )

    if step == "gold":
        if not st.session_state.gold_results:
            if st.session_state.joined_files:
                return (
                    80,
                    "🥇 Gold Layer",
                    "Data Enriched (Joined). "
                    "Waiting to generate insights...",
                )

            return (
                66,
                "🥇 Gold Layer",
                "Waiting to generate insights or enrich data...",
            )

        return (
            100,
            "🥇 Gold Layer",
            "Insights & Visualizations Generated! "
            "Pipeline Complete.",
        )

    return 0, "", ""


if st.session_state.step != "landing":
    pct, title, description = calculate_real_time_progress()

    with tracker_placeholder.container():
        t_col, c_col = st.columns([3, 1])

        with t_col:
            st.markdown(f"### {title}")
            st.write(f"**Status:** {description}")
            st.progress(pct)

        with c_col:
            fig = px.pie(
                values=[pct, max(0, 100 - pct)],
                names=["Completed", "Remaining"],
                hole=0.7,
                color_discrete_sequence=[
                    "#1f77b4",
                    "#e6e6e6",
                ],
            )

            fig.update_traces(
                textinfo="none",
                hoverinfo="none",
            )

            fig.update_layout(
                showlegend=False,
                margin=dict(t=5, b=5, l=5, r=5),
                height=100,
                annotations=[
                    dict(
                        text=f"{pct}%",
                        x=0.5,
                        y=0.5,
                        font_size=18,
                        font_weight="bold",
                        showarrow=False,
                    )
                ],
            )

            st.plotly_chart(
                fig,
                use_container_width=True,
                config={"displayModeBar": False},
            )

        st.divider()


# Execute the scroll only after all current-page content has rendered.
if step_changed:
    scroll_to_top()
    st.session_state.last_step = st.session_state.step
